version: "3"

services:
  sonarqube:
    # image: sonarqube:10.5.1-community
    image: sonarqube:lts-community
    # image: sonarqube:10.4.1-community
    command: -Dsonar.ce.javaOpts=-Xmx1192m -Dsonar.web.javaOpts=-Xmx1192m
    restart: unless-stopped
    container_name: sonarqube
    depends_on:
      - sonarqube_db
    ports:
      - "9000:9000"
    networks:
      - sonar-net
    environment:
      - SONARQUBE_JDBC_URL=jdbc:postgresql://sonarqube_db:5432/sonar
      - SONARQUBE_JDBC_USERNAME=sonar
      - SONARQUBE_JDBC_PASSWORD=sonar
    volumes:
      - ./docker/sonarqube/data:/opt/sonarqube/data
      - ./docker/sonarqube/extensions:/opt/sonarqube/extensions
      - ./docker/sonarqube/logs:/opt/sonarqube/logs

  sonarqube_db:
    # image: postgres:16
    image: postgres
    container_name: sonarqube_db
    restart: unless-stopped
    networks:
      - sonar-net
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
    volumes:
      - ./docker/postgres/postgresql:/var/lib/postgresql
      - ./docker/postgres/data:/var/lib/postgresql/data

networks:
  sonar-net:
    external: false