version: '3.4'

networks:
  devops-ic-collector-net:
    driver: bridge

services:
  devops-ci-collector-debug:
    env_file:
      - ../.env
    build:
      context: ./
      dockerfile: debug.Dockerfile
      target: debug
    volumes:
      - ..:/usr/src/app
    networks:
      - devops-ic-collector-net
    ports:
      - '3002:3002'
    container_name: devops-ci-collector-debug
    image: devops-ci-collector-debug:latest
    command: /bin/sh -c "while sleep 1000; do :; done"
    tty: true
