name: (Develop) CI

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  setup:
    name: Testing Application
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20.11.0
          cache: 'yarn'

      - name: Install dependencies
        run: yarn --frozen-lockfile

      # - name: Setting Environment Variables
      #   run: |
      #     cp .env.example .env

      - name: Running Lint
        run: yarn lint

      - name: Running Tests
        run: yarn test:unit

      - name: Building Application
        run: yarn build


        # # This workflow will build a golang project
# # For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

# name: Go

# on:
#   push:
#     branches: [ "develop" ]
#   pull_request:
#     branches: [ "develop" ]

# jobs:

#   build:
#     runs-on: ubuntu-latest
#     steps:
#     - uses: actions/checkout@v3

#     - name: Set up Go
#       uses: actions/setup-go@v4
#       with:
#         go-version: '1.20'

#     - name: Build
#       run: go build -v ./...

#     - name: Test
#       run: go test -v ./...
